/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvl_FFmpeg_jni_AVCodec */

#ifndef _Included_jvl_FFmpeg_jni_AVCodec
#define _Included_jvl_FFmpeg_jni_AVCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    findDecoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodec_findDecoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    findEncoderByName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodec_findEncoderByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    findEncoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodec_findEncoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getLongName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVCodec_getLongName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVCodec_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    allocateContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodec_allocateContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getPixelFormatsCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodec_getPixelFormatsCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getPixelFormat
 * Signature: (JI)Ljvl/FFmpeg/jni/AVPixelFormat;
 */
JNIEXPORT jobject JNICALL Java_jvl_FFmpeg_jni_AVCodec_getPixelFormat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getSampleFormatsCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodec_getSampleFormatsCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getSampleFormat
 * Signature: (JI)Ljvl/FFmpeg/jni/AVSampleFormat;
 */
JNIEXPORT jobject JNICALL Java_jvl_FFmpeg_jni_AVCodec_getSampleFormat
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
