/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvl_FFmpeg_jni_AVPacket */

#ifndef _Included_jvl_FFmpeg_jni_AVPacket
#define _Included_jvl_FFmpeg_jni_AVPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVPacket_allocate
  (JNIEnv *, jclass);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    unreference
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jvl_FFmpeg_jni_AVPacket_unreference
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    getPTS
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVPacket_getPTS
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    getDTS
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVPacket_getDTS
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    getPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVPacket_getPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    setPosition
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jvl_FFmpeg_jni_AVPacket_setPosition
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    getStreamIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVPacket_getStreamIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jvl_FFmpeg_jni_AVPacket_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    getSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVPacket_getSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVPacket
 * Method:    getData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jvl_FFmpeg_jni_AVPacket_getData
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
