/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvl_FFmpeg_jni_AVCodecParameters */

#ifndef _Included_jvl_FFmpeg_jni_AVCodecParameters
#define _Included_jvl_FFmpeg_jni_AVCodecParameters
#ifdef __cplusplus
extern "C" {
#endif
#undef jvl_FFmpeg_jni_AVCodecParameters_FF_PROFILE_UNKNOWN
#define jvl_FFmpeg_jni_AVCodecParameters_FF_PROFILE_UNKNOWN -99L
#undef jvl_FFmpeg_jni_AVCodecParameters_FF_LEVEL_UNKNOWN
#define jvl_FFmpeg_jni_AVCodecParameters_FF_LEVEL_UNKNOWN -99L
/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getCodecType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getCodecType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getProfileName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getProfileName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getProfile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getProfile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getChannels
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getSampleRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getBitrate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getBitrate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodecParameters
 * Method:    getCodecID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodecParameters_getCodecID
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
