/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvl_FFmpeg_jni_AVGlobal */

#ifndef _Included_jvl_FFmpeg_jni_AVGlobal
#define _Included_jvl_FFmpeg_jni_AVGlobal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvl_FFmpeg_jni_AVGlobal
 * Method:    getAVErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVGlobal_getAVErrorString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
