/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvl_FFmpeg_jni_AVCodec */

#ifndef _Included_jvl_FFmpeg_jni_AVCodec
#define _Included_jvl_FFmpeg_jni_AVCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    findDecoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodec_findDecoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getLongName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVCodec_getLongName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVCodec_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    allocateContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jvl_FFmpeg_jni_AVCodec_allocateContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    copyParamsToContext
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodec_copyParamsToContext
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVCodec
 * Method:    open
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVCodec_open
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
