/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvl_FFmpeg_jni_AVStream */

#ifndef _Included_jvl_FFmpeg_jni_AVStream
#define _Included_jvl_FFmpeg_jni_AVStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvl_FFmpeg_jni_AVStream
 * Method:    isForced
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jvl_FFmpeg_jni_AVStream_isForced
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVStream
 * Method:    isDefault
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jvl_FFmpeg_jni_AVStream_isDefault
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVStream
 * Method:    getFramerateNumerator
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVStream_getFramerateNumerator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVStream
 * Method:    getFramerateDenominator
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jvl_FFmpeg_jni_AVStream_getFramerateDenominator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVStream
 * Method:    debug
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVStream_debug
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jvl_FFmpeg_jni_AVStream
 * Method:    getLanguage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jvl_FFmpeg_jni_AVStream_getLanguage
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
